config/routes.rb
Rails.application.routes.draw do
    root 'home#welcome'
    #metoda http, potem sciezka (strukutra po /), gdzie rootuje,
    # get '/autors', to: 'autors#index', as: :autors
    # get '/autors/:id', to: 'autors#show', as: :autor
    # get '/autor/new', to: 'autors#new', as: :new_autor
    resources :autors
    resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ActiveRecord::Base
  validates :name, :surname, presence: true
  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 5}

  has_many :comments
end

app/models/author_comment.rb
class AuthorComment < ActiveRecord::Base
  belongs_to :author
  belongs_to :comment
end

app/models/autor.rb
class Autor < ActiveRecord::Base
  validates :name, :surname, presence: true
  validates :name, length: { minimum: 2 }
  validates :surname, length: { minimum: 2}
  has_many :posts
  # has_many :autor_posts
  # has_many :posts, through: :autor_posts

  scope :old, ->{ where('age > 30')}
  scope :young, ->{ where('age < 20')}
  before_create :default_age

# nie musimy pisac return bo bedzie automatycznie zwrocona
  def fullname
    "#{name} #{surname}"
  end


  private

  def default_age
    self.age = 25 unless age
  end

end

app/models/autor_post.rb
class AutorPost < ActiveRecord::Base
  belongs_to :autor
  belongs_to :post
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, :author, presence: true
  validates :body, length: { maximum: 180 }

  belongs_to :author
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :content, presence: true
  validates :title, length: { maximum: 80 }
  validates :content, length: { in: 10..500 }

  scope :old, -> {where('created_at < ?', 40.minutes.ago)}
  scope :short, -> {where('LENGTH(content) < 20')}


  belongs_to :autor


  def post_title
    "#{title}"
  end


  # has_many :autor_posts
  # has_many :autors, through: :autor_posts
  # before_create :annotate_autor
  #
  # def annotate_autor
  #   self.autor = "#{self.autor} from Binarapps"
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController

  @autorstry = Autor.all

  def index
    #zmienna lokalna, nie jest widoczna w widoku, wiec robimy zmienna instacji
    @autors = Autor.all
    @autor = Autor.new #przenieslismy formularz new na index
  end

  def show
    #chcemy znalezc konkretnego autora po id, z URL, /autors/xx
    @autor = Autor.find(params[:id])
  end

  def new
    @autor = Autor.new
  end

# redirect robi pelne przekierowanie, render nie robi prawie nic,
# bierze tylko caly html i wkleja cos innego
  def create
    @autor = Autor.create(autor_params)
  end

  def edit
    @autor = Autor.find(params[:id])
  end

  def update
    @autor = Autor.find(params[:id])
      if @autor.update(autor_params)
        redirect_to autors_path,  notice: 'Author was updated'
      else
        render :edit
      end
  end

  def destroy
    # autor = Autor.find(params[:id])
    # if autor.destroy
    #   redirect_to autors_path, notice: 'Author was deleted'
    # else
    #   redirect_to autors_path, alert: 'Error'
    # end

    @autor = Autor.find(params[:id])
    @autor.destroy
  end


  private

  def autor_params
      params.require(:autor).permit(:name, :surname, :age)
  end



end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # def index
  #   @posts = Post.all

  def post
  end

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end


  def update
    @post = Post.find(params[:id])
      if @post.update(post_params)
        redirect_to posts_path,  notice: 'Post was updated'
      else
        render :edit
      end
  end


  def create
    @post = Post.new(post_params)
      if @post.save
        redirect_to posts_path, notice: 'Post created'
      else
        redirect_to posts_path, alert: 'Something went wrong'
      end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to posts_path, notice: 'Post was deleted'
    else
      redirect_to posts_path, alert: 'Error'
    end
  end



  private

  def post_params
      params.require(:post).permit(:title, :content, :autor_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/autors/_autor.html.erb
<div class="row" data-autor-id="<%= autor.id %>">
  <!-- railsowa metoda pomocnicza, co wyswietlone, gdzie przeniesie -->
  <div class="col-sm-12 col-md-9"><%= link_to autor.fullname, autor_path(id: autor.id) %></div>
  <div class="col-md-3">
    <%= link_to 'Edit', edit_autor_path(id: autor.id),role: 'button', class:'btn btn-primary text-center' %>
    <%= link_to 'Delete', autor_path(id: autor.id), method: :delete, remote: true, data: { confirm: 'Are you sure?' }, role: 'button', class:'btn btn-danger text-center' %>
  </div>
</div>

app/views/autors/_form.erb
<%=  form_for @autor, remote: true, html: { class: "new-autor" }  do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control col-md-2 col-centered text-center", placeholder: "Enter your name"%>
    <small id="nameHelpBlock" class="form-text text-muted">
      Your name must be at least 2 characters long.
    </small>
  </div>

  <div class="form-group">
    <%= f.label :surname, class: "control-label" %>
    <%= f.text_field :surname, class: "form-control col-md-2 col-centered text-center", placeholder: "Enter your surname" %>
    <small id="surnameHelpBlock" class="form-text text-muted">
      also at least 2 characters
    </small>
  </div>

  <div class="form-group">
    <%= f.label :age, class: "control-label" %>
    <%= f.number_field :age, class: "form-control col-md-1 col-centered text-center"%>
    <small id="ageHelpBlock" class="form-text text-muted">
      You can lie :)
    </small>
  </div>

  <%= f.submit 'save', role: 'button', class:'btn btn-outline-success' %>
<% end %>

app/views/autors/create.js.erb
<% if @autor.persisted? %>
  $('.autors').append('<%= escape_javascript render 'autor', autor: @autor%>')
<% else %>
  alert('Try again');
<% end %>

$('.new-autor').find('input[type="text"], input[type="number"]').val('');

app/views/autors/destroy.js.erb
$('[data-autor-id="<%= @autor.id %>"]').remove();

app/views/autors/edit.html.erb
<h1 class="edit-header text-center">Edit author</h1>
<!-- wyglada tak samo jak new -->
<!-- dlatego uzyjemy _form.erb -->
<%= render 'form' %>

app/views/autors/index.html.erb
<div class="header-autors">
  <h1 class="text-center">List of all authors</h1>
</div>

<img style="display: none;" src="https://loading.io/spinners/balls/lg.circle-slack-loading-icon.gif"/>

<div class="container autors">
  <% @autors.each do |autor| %>
  <!-- kazdy row ma zawsze 12 kolumn -->
    <%= render 'autor', autor: autor %>
  <% end %>
</div>

<!-- <div class="text-center"><%= link_to 'Add new author', new_autor_path, role: 'button', class:'btn btn-outline-success' %></div> -->
<p class="new-author-p text-center"> You can add new author below: </p>

<!-- forumlarze metodami pomocniczymu -->
<!--<%=  form_for @autor, remote: true, html: { class: "new-autor" }  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :surname %>
  <%= f.text_field :surname %>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <%= f.submit 'Save' %>
<% end %> -->

<%=  form_for @autor, remote: true, html: { class: "new-autor" }  do |f| %>
  <div class="form-group">
    <%= f.label :name, class: "control-label" %>
    <%= f.text_field :name, class: "form-control col-md-2 col-centered text-center", placeholder: "Enter your name"%>
    <small id="nameHelpBlock" class="form-text text-muted">
      Your name must be at least 2 characters long.
    </small>
  </div>

  <div class="form-group">
    <%= f.label :surname, class: "control-label" %>
    <%= f.text_field :surname, class: "form-control col-md-2 col-centered text-center", placeholder: "Enter your surname" %>
    <small id="surnameHelpBlock" class="form-text text-muted">
      also at least 2 characters
    </small>
  </div>

  <div class="form-group">
    <%= f.label :age, class: "control-label" %>
    <%= f.number_field :age, class: "form-control col-md-1 col-centered text-center"%>
    <small id="ageHelpBlock" class="form-text text-muted">
      You can lie :)
    </small>
  </div>
  <!-- <hr /> -->
  <%= f.submit 'save', role: 'button', class:'btn btn-outline-success' %>
<% end %>


<% if @autor.errors.any? %>
  <ul>
    <% @autor.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/autors/new.html.erb
<h1 class="new-author-header text-center">Add new author</h1>

<%= render 'form' %>

app/views/autors/show.html.erb
<h1 class="show-autor text-center">
 <%= "hi #{@autor.fullname}!" %>
</h1>

<div class="info-autor">
  <div class="age-label">
    Age:
    <p class="age-value"><%= @autor.age%></p>
  </div>
  <hr />
  <div class="date-label">
    Created at:
    <p class="date-value"><%= @autor.created_at%></p>
  </div>
  <hr />
  <div class="update-label">
    Updated at:
    <p class="update-value"><%= @autor.updated_at%></p>
  </div>
  <%= link_to 'Back to authors', autors_path, role: 'button', class:'btn btn-outline-success'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/css/bootstrap.min.css" integrity="sha384-Smlep5jCw/wG7hdkwQ/Z5nLIefveQRIY9nfy6xoR1uRYBtpZgI6339F5dgvm/e9B" crossorigin="anonymous">
    <title>Blog MJ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- korzystanie z partiali -->
    <%= render 'layouts/partials/navbar' %>
    <%= render 'layouts/partials/flash', flash: flash %>
    <%= yield %>
  </body>
</html>

app/views/layouts/partials/_flash.html.haml
- if alert
  .alert.alert-danger
    Alert: #{alert}
- if notice
  .alert.alert-success
    Success: #{notice}

app/views/layouts/partials/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-custom">
  <%= link_to root_path do %>
  <img class="navbar-logo" src="https://cdn.iconscout.com/public/images/icon/free/png-512/donut-doughnut-sweet-dessert-food-fastfood-emoj-symbol-36d114726913e9a6-512x512.png" width="40" height="40">
  <% end %>
  <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/autors#index">Authors</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/posts#index">Posts</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          List of authors
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Add new author', new_autor_path, role: 'button', class: 'dropdown-item' %>
          <div class="dropdown-divider"></div>
            <% Autor.all.each do |f| %>
              <%= link_to f.fullname, autor_path(id: f.id), class: 'dropdown-item' %>
            <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/posts/_form.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li>
        <%= msg %>
      </li>
    <% end %>
  </ul>
<% end %>

<!-- forumlarze metodami pomocniczymu -->
<%=  form_for @post, remote: true, html: { class: "new-post" } do |f| %>
  <div class="form-group">
    <%= f.label :title, class: "control-label" %>
    <%= f.text_field :title, class: "form-control col-md-2 text-center col-centered", placeholder: "Enter post title" %>
  </div>

  <div class="form-group">
    <%= f.label :content, class: "control-label" %>
    <%= f.text_area :content, class: "form-control col-md-2 text-center col-centered", placeholder: "What's on your mind?"  %>
  </div>

  <div class="form-group">
    <%= f.label :autor_id, class:"control-label" %>
    <%= f.collection_select(:autor_id, Autor.all, :id, :name, { :class => 'form-control'})  %>
    <small id="authorChoiceHelpBlock" class="form-text text-muted">
      Choose your name
    </small>
    <hr />
  </div>
  <%= f.submit 'save', role: 'button', class:'btn btn-outline-success' %>
<% end %>

app/views/posts/edit.html.erb
<div class="header-edit text-center">
  <h1> Edit post </h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="header-posts text-center">
  <h1>All posts</h1>
</div>

<div class="container">
  <% @posts.each do |post| %>
  <div class="row" data-post-id="<%= post.id %>">
       <div class="col-md-8"><%= link_to post.post_title, post_path(id: post.id) %></div>
       <!-- <%= "treść: #{post.content} autor(id): #{post.autor_id}" %> -->
       <div class="col-md-3">
         <%= link_to 'Edit', edit_post_path(id: post.id), role: 'button', class:'btn btn-primary text-center' %>
         <%= link_to 'Delete', post_path(id: post.id), method: :delete, data: { confirm: 'Are you sure?' }, role: 'button', class:'btn btn-danger text-center' %>
      </div>
   </div>
 <% end %>
</div>

<div class="text-center"><%= link_to 'Add new post', new_post_path, role: 'button', class:'btn btn-outline-success' %></div>

app/views/posts/new.html.erb
<h1 class="text-center">Add new post</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1 class="show-post text-center">
  Tytuł:
</h1>

<h2 class="post-title text-center">
  <%= @post.post_title %>
</h2>

<div class="info-post">
  <div class="content-label">
    Content:
    <p class="content-value"><%= @post.content%></p>
  </div>
  <hr />
  <div class="autor-label">
    Autor id:
    <p class="autor-value"><%= @post.autor_id%></p>
  </div>
  <hr />
  <div class="dates-label">
    Created at:
    <p class="dates-values"><%= @post.created_at%></p>
  </div>
  <hr />
  <div class="update-label">
    Updated at:
    <p class="update-post"><%= @post.updated_at%></p>
  </div>
  <%= link_to 'Back to all posts', posts_path, role: 'button', class:'btn btn-outline-success'%>
</div>